// Generated by scripts/generate-runner-experimental-api-metadata.mjs.
export const experimentalApiMetadata: Record<string, { successStatuses: number[]; boardOnly: boolean; source: string }> = {
  "GET /api/companies/{companyId}/pipelines": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/companies/{companyId}/pipelines-attention": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/companies/{companyId}/case-events": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/companies/{companyId}/pipelines": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/companies/{companyId}/review-cases": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/companies/{companyId}/review-cases/bulk": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/pipelines/{pipelineId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/pipelines/{pipelineId}/health": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/pipelines/{pipelineId}/intake-form": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PATCH /api/pipelines/{pipelineId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/pipelines/{pipelineId}/stages": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PATCH /api/pipelines/{pipelineId}/stages/{stageId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PATCH /api/pipelines/{pipelineId}/stages/{stageId}/automation-env": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "DELETE /api/pipelines/{pipelineId}/stages/{stageId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PUT /api/pipelines/{pipelineId}/transitions": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/pipelines/{pipelineId}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PUT /api/pipelines/{pipelineId}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/pipelines/{pipelineId}/documents/{key}/revisions": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/pipelines/{pipelineId}/documents/{key}/revisions/{revisionId}/restore": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/pipelines/{pipelineId}/cases": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/pipelines/{pipelineId}/cases/batch": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/breakdown": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/pipelines/{pipelineId}/cases": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PUT /api/cases/{caseId}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/documents/{key}/revisions": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/documents/{key}/revisions/{revisionId}/restore": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/children": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PATCH /api/cases/{caseId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/claim": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/release": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/transition": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/suggest-transition": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/resolve-suggestion": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/acknowledge-drift": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/review": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "PUT /api/cases/{caseId}/blockers": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/open-conversation": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/issue-links": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/outputs": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/issue-links": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "DELETE /api/cases/{caseId}/issue-links/{linkId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/events": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/children/tree": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/rollup": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/context-pack": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "GET /api/cases/{caseId}/automation/retry-plan": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/automation/retry": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/automations/{automationId}/retry": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/cases/{caseId}/automation/current-stage/rerun": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/pipelines.ts"
  },
  "POST /api/companies/{companyId}/cases": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/companies/{companyId}/cases": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/cases/{id}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/cases/{id}/documents/{key}/annotations": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/cases/{id}/documents/{key}/annotations/{threadId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/documents/{key}/annotations": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/documents/{key}/annotations/{threadId}/comments": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "PATCH /api/cases/{id}/documents/{key}/annotations/{threadId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "PUT /api/cases/{id}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/documents/{key}/lock": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/documents/{key}/unlock": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/documents/{key}/revisions/{revisionId}/restore": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "DELETE /api/cases/{id}/documents/{key}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/links": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "POST /api/cases/{id}/attachments": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/cases/{id}/events": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/cases/{id}/documents/{key}/revisions": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/issues/{issueId}/cases": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/cases/{id}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "PATCH /api/cases/{id}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/cases.ts"
  },
  "GET /api/companies/{companyId}/smoke-lab/oauth/authorize": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/oauth/authorize": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/oauth/token": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "GET /api/companies/{companyId}/smoke-lab/oauth/userinfo": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/oauth/revoke": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "GET /api/companies/{companyId}/smoke-lab/services": {
    "successStatuses": [
      200
    ],
    "boardOnly": true,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/services/start": {
    "successStatuses": [
      200
    ],
    "boardOnly": true,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/services/stop": {
    "successStatuses": [
      200
    ],
    "boardOnly": true,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/install-fixtures": {
    "successStatuses": [
      200
    ],
    "boardOnly": true,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "GET /api/companies/{companyId}/smoke-lab/runs": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/runs": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "GET /api/companies/{companyId}/smoke-lab/runs/{runId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "PATCH /api/companies/{companyId}/smoke-lab/runs/{runId}": {
    "successStatuses": [
      200
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/runs/{runId}/steps": {
    "successStatuses": [
      201
    ],
    "boardOnly": false,
    "source": "server/src/routes/smoke-lab.ts"
  },
  "POST /api/companies/{companyId}/smoke-lab/reset": {
    "successStatuses": [
      200
    ],
    "boardOnly": true,
    "source": "server/src/routes/smoke-lab.ts"
  }
};
