// Experimental routes share their runtime validators with OpenAPI discovery.
import { z } from "zod";
import * as pipelineSchemas from "./pipelines-schemas.js";
import * as caseSchemas from "./cases-schemas.js";
import * as sharedSchemas from "@paperclipai/shared";

export const experimentalApiPaths: readonly [string, string, z.ZodTypeAny | undefined][] = [
  ["get", "/api/companies/{companyId}/pipelines", undefined],
  ["get", "/api/companies/{companyId}/pipelines-attention", undefined],
  ["get", "/api/companies/{companyId}/case-events", undefined],
  ["post", "/api/companies/{companyId}/pipelines", pipelineSchemas.createPipelineSchema],
  ["get", "/api/companies/{companyId}/review-cases", undefined],
  ["post", "/api/companies/{companyId}/review-cases/bulk", pipelineSchemas.bulkReviewSchema],
  ["get", "/api/pipelines/{pipelineId}", undefined],
  ["get", "/api/pipelines/{pipelineId}/health", undefined],
  ["get", "/api/pipelines/{pipelineId}/intake-form", undefined],
  ["patch", "/api/pipelines/{pipelineId}", pipelineSchemas.updatePipelineSchema],
  ["post", "/api/pipelines/{pipelineId}/stages", pipelineSchemas.createStageSchema],
  ["patch", "/api/pipelines/{pipelineId}/stages/{stageId}", pipelineSchemas.updateStageSchema],
  ["patch", "/api/pipelines/{pipelineId}/stages/{stageId}/automation-env", pipelineSchemas.updateStageAutomationEnvSchema],
  ["delete", "/api/pipelines/{pipelineId}/stages/{stageId}", undefined],
  ["put", "/api/pipelines/{pipelineId}/transitions", pipelineSchemas.replaceTransitionsSchema],
  ["get", "/api/pipelines/{pipelineId}/documents/{key}", undefined],
  ["put", "/api/pipelines/{pipelineId}/documents/{key}", pipelineSchemas.upsertPipelineDocumentSchema],
  ["get", "/api/pipelines/{pipelineId}/documents/{key}/revisions", undefined],
  ["post", "/api/pipelines/{pipelineId}/documents/{key}/revisions/{revisionId}/restore", undefined],
  ["post", "/api/pipelines/{pipelineId}/cases", pipelineSchemas.ingestCaseSchema],
  ["post", "/api/pipelines/{pipelineId}/cases/batch", pipelineSchemas.batchIngestSchema],
  ["post", "/api/cases/{caseId}/breakdown", pipelineSchemas.breakdownCaseSchema],
  ["get", "/api/pipelines/{pipelineId}/cases", undefined],
  ["get", "/api/cases/{caseId}", undefined],
  ["get", "/api/cases/{caseId}/documents/{key}", undefined],
  ["put", "/api/cases/{caseId}/documents/{key}", pipelineSchemas.upsertPipelineCaseDocumentSchema],
  ["get", "/api/cases/{caseId}/documents/{key}/revisions", undefined],
  ["post", "/api/cases/{caseId}/documents/{key}/revisions/{revisionId}/restore", undefined],
  ["get", "/api/cases/{caseId}/children", undefined],
  ["patch", "/api/cases/{caseId}", pipelineSchemas.casePatchSchema],
  ["post", "/api/cases/{caseId}/claim", pipelineSchemas.claimCaseSchema],
  ["post", "/api/cases/{caseId}/release", pipelineSchemas.releaseCaseSchema],
  ["post", "/api/cases/{caseId}/transition", pipelineSchemas.transitionCaseSchema],
  ["post", "/api/cases/{caseId}/suggest-transition", pipelineSchemas.suggestTransitionSchema],
  ["post", "/api/cases/{caseId}/resolve-suggestion", pipelineSchemas.resolveSuggestionSchema],
  ["post", "/api/cases/{caseId}/acknowledge-drift", pipelineSchemas.acknowledgeDriftSchema],
  ["post", "/api/cases/{caseId}/review", pipelineSchemas.reviewCaseSchema],
  ["put", "/api/cases/{caseId}/blockers", pipelineSchemas.blockersSchema],
  ["post", "/api/cases/{caseId}/open-conversation", undefined],
  ["get", "/api/cases/{caseId}/issue-links", undefined],
  ["get", "/api/cases/{caseId}/outputs", undefined],
  ["post", "/api/cases/{caseId}/issue-links", pipelineSchemas.createIssueLinkSchema],
  ["delete", "/api/cases/{caseId}/issue-links/{linkId}", undefined],
  ["get", "/api/cases/{caseId}/events", undefined],
  ["get", "/api/cases/{caseId}/children/tree", undefined],
  ["get", "/api/cases/{caseId}/rollup", undefined],
  ["get", "/api/cases/{caseId}/context-pack", undefined],
  ["get", "/api/cases/{caseId}/automation/retry-plan", undefined],
  ["post", "/api/cases/{caseId}/automation/retry", sharedSchemas.pipelineAutomationRetryRequestSchema],
  ["post", "/api/cases/{caseId}/automations/{automationId}/retry", undefined],
  ["post", "/api/cases/{caseId}/automation/current-stage/rerun", undefined],
  ["post", "/api/companies/{companyId}/cases", caseSchemas.createCaseSchema],
  ["get", "/api/companies/{companyId}/cases", undefined],
  ["get", "/api/cases/{id}/documents/{key}", undefined],
  ["get", "/api/cases/{id}/documents/{key}/annotations", undefined],
  ["get", "/api/cases/{id}/documents/{key}/annotations/{threadId}", undefined],
  ["post", "/api/cases/{id}/documents/{key}/annotations", sharedSchemas.createDocumentAnnotationThreadSchema],
  ["post", "/api/cases/{id}/documents/{key}/annotations/{threadId}/comments", sharedSchemas.createDocumentAnnotationCommentSchema],
  ["patch", "/api/cases/{id}/documents/{key}/annotations/{threadId}", sharedSchemas.updateDocumentAnnotationThreadSchema],
  ["put", "/api/cases/{id}/documents/{key}", caseSchemas.upsertCaseDocumentSchema],
  ["post", "/api/cases/{id}/documents/{key}/lock", undefined],
  ["post", "/api/cases/{id}/documents/{key}/unlock", undefined],
  ["post", "/api/cases/{id}/documents/{key}/revisions/{revisionId}/restore", undefined],
  ["delete", "/api/cases/{id}/documents/{key}", undefined],
  ["post", "/api/cases/{id}/links", caseSchemas.createIssueLinkSchema],
  ["post", "/api/cases/{id}/attachments", undefined],
  ["get", "/api/cases/{id}/events", undefined],
  ["get", "/api/cases/{id}/documents/{key}/revisions", undefined],
  ["get", "/api/issues/{issueId}/cases", undefined],
  ["get", "/api/cases/{id}", undefined],
  ["patch", "/api/cases/{id}", caseSchemas.patchCaseSchema],
  ["get", "/api/companies/{companyId}/smoke-lab/oauth/authorize", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/oauth/authorize", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/oauth/token", undefined],
  ["get", "/api/companies/{companyId}/smoke-lab/oauth/userinfo", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/oauth/revoke", undefined],
  ["get", "/api/companies/{companyId}/smoke-lab/services", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/services/start", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/services/stop", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/install-fixtures", undefined],
  ["get", "/api/companies/{companyId}/smoke-lab/runs", undefined],
  ["post", "/api/companies/{companyId}/smoke-lab/runs", sharedSchemas.createSmokeRunSchema],
  ["get", "/api/companies/{companyId}/smoke-lab/runs/{runId}", undefined],
  ["patch", "/api/companies/{companyId}/smoke-lab/runs/{runId}", sharedSchemas.updateSmokeRunSchema],
  ["post", "/api/companies/{companyId}/smoke-lab/runs/{runId}/steps", sharedSchemas.recordSmokeRunStepSchema],
  ["post", "/api/companies/{companyId}/smoke-lab/reset", undefined],
];

// Query contracts shared with the runtime parser where one exists.
export const experimentalApiQueries: Record<string, z.ZodObject<any>> = {
  "GET /api/companies/{companyId}/cases": caseSchemas.listCasesQuerySchema,
  "GET /api/cases/{id}/events": caseSchemas.listEventsQuerySchema,
  "GET /api/cases/{caseId}/automation/retry-plan": pipelineSchemas.retryAutomationQuerySchema,
  "GET /api/companies/{companyId}/pipelines-attention": z.object({ limit: z.coerce.number().int().positive().optional() }),
  "GET /api/companies/{companyId}/case-events": z.object({ types: z.string().optional(), limit: z.coerce.number().int().positive().optional(), offset: z.coerce.number().int().nonnegative().optional() }),
  "GET /api/companies/{companyId}/review-cases": z.object({ pipelineId: z.string().optional(), parentCaseId: z.string().optional() }),
  "GET /api/pipelines/{pipelineId}/cases": z.object({ stageKey: z.string().optional(), q: z.string().optional(), terminal: z.enum(["true", "false"]).optional(), includeRetired: z.enum(["true", "false"]).optional(), parentCaseId: z.string().optional() }),
  "DELETE /api/pipelines/{pipelineId}/stages/{stageId}": z.object({ moveCasesToStageId: z.string().optional() }),
};
