// Generated from ui/src/assets/cliplab/onboarding.character.json by scripts/sync-cliplab-character.mjs. Do not edit.
import type { Definition } from "./model.js";

/** The persona character: Tonio's ClipLab studio export, every palette recolours its body. */
export const PAPERCLIP_CHARACTER: Definition = {
  "version": 1,
  "character": {
    "id": "character-5128bda1",
    "name": "Milo copy",
    "shape": "cap",
    "color": "#0f57ff",
    "color2": "#4deaff",
    "gradient": true,
    "gradientAngle": 20,
    "toon": true,
    "trueFront": false,
    "lockPosition": true,
    "eyeColor": "#172023",
    "iris": false,
    "elevated": true,
    "elevation": 0.115,
    "shadow": true,
    "motion": 0.45,
    "speed": 1,
    "blink": true,
    "blinkInterval": 6,
    "followCursor": false,
    "followRotation": false
  },
  "expressions": [
    {
      "id": "idle",
      "name": "Idle",
      "description": "A little breath. A quiet smile.",
      "beats": [
        {
          "id": "idle-1",
          "name": "Settle",
          "duration": 1.8,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1.12,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.74,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1.6
          }
        },
        {
          "id": "idle-2",
          "name": "Look around",
          "duration": 1.4,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0.22,
            "gazeY": 0,
            "mouthWidth": 1.12,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 9,
            "rotationZ": -3,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1.6
          }
        },
        {
          "id": "idle-3",
          "name": "Return",
          "duration": 1,
          "pose": {
            "eye": "dot",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1.12,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 33,
            "rightY": 33,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 8,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1.6
          }
        },
        {
          "id": "beat-57cf6bfb",
          "name": "Look around",
          "duration": 1.4,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0.22,
            "gazeY": 0,
            "mouthWidth": 1.12,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 5,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1.6
          }
        }
      ]
    },
    {
      "id": "listening",
      "name": "Listening",
      "description": "Present, curious, and all ears.",
      "beats": [
        {
          "id": "listen-1",
          "name": "Notice",
          "duration": 1.2,
          "pose": {
            "eye": "wide",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1.06,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": -4,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "listen-2",
          "name": "Lean in",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1.13,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": -7,
            "rotationY": 0,
            "rotationZ": 6,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "listen-3",
          "name": "Nod",
          "duration": 1.1,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 5,
            "rotationY": 0,
            "rotationZ": 3,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "thinking",
      "name": "Thinking",
      "description": "A glance up. Something is taking shape.",
      "beats": [
        {
          "id": "think-1",
          "name": "Wonder",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "oh",
            "prop": "question",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0.6,
            "gazeY": 0.55,
            "mouthWidth": 0.6,
            "mouthOpen": 0.23,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -7,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "think-2",
          "name": "Consider",
          "duration": 1.6,
          "pose": {
            "eye": "soft",
            "mouth": "wave",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": -0.35,
            "gazeY": 0.2,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": -8,
            "rotationZ": 4,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "think-3",
          "name": "Almost",
          "duration": 1.2,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0.25,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -3,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "working",
      "name": "Working",
      "description": "Small, focused, steady movements.",
      "beats": [
        {
          "id": "work-1",
          "name": "Focus left",
          "duration": 1,
          "pose": {
            "eye": "soft",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": -0.5,
            "gazeY": -0.3,
            "mouthWidth": 0.65,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": -7,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "work-2",
          "name": "Focus right",
          "duration": 1,
          "pose": {
            "eye": "soft",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0.5,
            "gazeY": -0.3,
            "mouthWidth": 0.65,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 7,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "work-3",
          "name": "Check",
          "duration": 1.4,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": -3,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "happy",
      "name": "Happy",
      "description": "A small open smile says it all.",
      "beats": [
        {
          "id": "happy-1",
          "name": "Light up",
          "duration": 0.9,
          "pose": {
            "eye": "dot",
            "mouth": "open",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -5,
            "squash": 1.025,
            "tongue": true,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "happy-2",
          "name": "Delight",
          "duration": 1.3,
          "pose": {
            "eye": "closed",
            "mouth": "open",
            "prop": "sparkle",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.75,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 5,
            "squash": 0.97,
            "tongue": true,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "happy-3",
          "name": "Glow",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "open",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.45,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -2,
            "squash": 1,
            "tongue": true,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "confused",
      "name": "Confused",
      "description": "A little uneven. A second look.",
      "beats": [
        {
          "id": "confused-1",
          "name": "Wait",
          "duration": 1.2,
          "pose": {
            "eye": "soft",
            "mouth": "wave",
            "prop": "question",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 0.7,
            "rightScale": 1.1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 10,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "confused-2",
          "name": "Really?",
          "duration": 1.4,
          "pose": {
            "eye": "dot",
            "mouth": "oh",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1.1,
            "rightScale": 0.7,
            "gazeX": -0.2,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.25,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -9,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "confused-3",
          "name": "Hmm",
          "duration": 1.3,
          "pose": {
            "eye": "soft",
            "mouth": "frown",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 0.75,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 4,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "sleepy",
      "name": "Sleepy",
      "description": "Slow breathing, drifting sleep marks.",
      "beats": [
        {
          "id": "sleep-1",
          "name": "Doze",
          "duration": 2,
          "pose": {
            "eye": "closed",
            "mouth": "sleep",
            "prop": "zzz",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 0,
            "rotationZ": -6,
            "squash": 0.97,
            "tongue": false,
            "teeth": false,
            "drool": true,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "sleep-2",
          "name": "Breathe in",
          "duration": 2,
          "pose": {
            "eye": "closed",
            "mouth": "oh",
            "prop": "zzz",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 0.65,
            "mouthOpen": 0.25,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -3,
            "squash": 1.025,
            "tongue": false,
            "teeth": false,
            "drool": true,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "sleep-3",
          "name": "Breathe out",
          "duration": 2,
          "pose": {
            "eye": "closed",
            "mouth": "sleep",
            "prop": "zzz",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -7,
            "squash": 0.98,
            "tongue": false,
            "teeth": false,
            "drool": true,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "playful",
      "name": "Playful",
      "description": "A wink, a grin, a little mischief.",
      "beats": [
        {
          "id": "play-1",
          "name": "Peek",
          "duration": 1.1,
          "pose": {
            "eye": "dot",
            "mouth": "open",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": -10,
            "rotationZ": -8,
            "squash": 1,
            "tongue": true,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "play-2",
          "name": "Wink",
          "duration": 1.2,
          "pose": {
            "eye": "wink",
            "mouth": "open",
            "prop": "sparkle",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.7,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 9,
            "squash": 1,
            "tongue": true,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "play-3",
          "name": "Grin",
          "duration": 1.3,
          "pose": {
            "eye": "dot",
            "mouth": "open",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.45,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": -3,
            "squash": 1,
            "tongue": false,
            "teeth": true,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "loading",
      "name": "Loading",
      "description": "A slow start, one gradient turn, then a half-second rest.",
      "poseExpressionId": "working",
      "beats": [
        {
          "id": "loading-rotate",
          "name": "Rotate",
          "duration": 2,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          },
          "gradientAction": "rotate",
          "gradientTurns": 4
        }
      ]
    },
    {
      "id": "expression-7287c053",
      "name": "Idle side to side 01",
      "description": "",
      "beats": [
        {
          "id": "beat-3b4f9de9",
          "name": "Begin",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-9516b036",
          "name": "Beat 4",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 11,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-c3858187",
          "name": "turn",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 39,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-41ccd5c0",
          "name": "Retur",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "expression-f9a89083",
      "name": "Idle side to side 02",
      "description": "",
      "beats": [
        {
          "id": "beat-f9434a07",
          "name": "Begin",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 48,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-68deb476",
          "name": "Beat 4",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 11,
            "rotationY": 38,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-5c04098e",
          "name": "Beat 4",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": -5,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-9546ee11",
          "name": "turn",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 26,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "expression-b20a0ef7",
      "name": "Idle side to side 03",
      "description": "",
      "beats": [
        {
          "id": "beat-1b2247b8",
          "name": "Begin",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 20,
            "rotationY": 38,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-1df49105",
          "name": "Beat 4",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": -8,
            "rotationY": 44,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-2b9fa4f3",
          "name": "turn",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "line",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 26,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-8bb4cc3c",
          "name": "Beat 4",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 12,
            "rotationY": -4,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        }
      ]
    },
    {
      "id": "expression-229a39b6",
      "name": "Sleepy to wake",
      "description": "Slow breathing, drifting sleep marks.",
      "beats": [
        {
          "id": "beat-3460c6a3",
          "name": "Doze",
          "duration": 1,
          "pose": {
            "eye": "closed",
            "mouth": "sleep",
            "prop": "zzz",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1.2,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 4,
            "rotationY": 0,
            "rotationZ": -6,
            "squash": 0.97,
            "tongue": false,
            "teeth": false,
            "drool": true,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1.2
          }
        },
        {
          "id": "beat-8b5d3238",
          "name": "Breathe in",
          "duration": 0.5,
          "pose": {
            "eye": "wide",
            "mouth": "oh",
            "prop": "question",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 0.65,
            "mouthOpen": 1,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": -3,
            "rotationY": 0,
            "rotationZ": -3,
            "squash": 1.025,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-c35e2a7e",
          "name": "Breathe in",
          "duration": 1,
          "pose": {
            "eye": "wide",
            "mouth": "oh",
            "prop": "question",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 0.65,
            "mouthOpen": 1,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": 11,
            "rotationY": 30,
            "rotationZ": -3,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1
          }
        },
        {
          "id": "beat-787f488e",
          "name": "Wink",
          "duration": 1.2,
          "pose": {
            "eye": "wink",
            "mouth": "open",
            "prop": "sparkle",
            "propSize": 1.45,
            "propCount": 3,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 0.59,
            "mouthOpen": 0.71,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.75,
            "faceY": 0,
            "rotationX": -11,
            "rotationY": 9,
            "rotationZ": 11,
            "squash": 1.05,
            "tongue": true,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 0.85
          }
        },
        {
          "id": "beat-2cafeefa",
          "name": "Settle",
          "duration": 1.5,
          "pose": {
            "eye": "dot",
            "mouth": "smile",
            "prop": "none",
            "propSize": 1,
            "propCount": 0,
            "propOutward": 1,
            "faceSet": "set-1",
            "brows": "none",
            "browStroke": 1,
            "browLength": 1,
            "blush": 0,
            "eyeSize": 1,
            "eyeHeight": 1,
            "spacing": 1,
            "eyeTilt": 0,
            "leftScale": 1,
            "rightScale": 1,
            "gazeX": 0,
            "gazeY": 0,
            "mouthWidth": 1.12,
            "mouthOpen": 0.5,
            "leftX": 0,
            "rightX": 0,
            "leftY": 0,
            "rightY": 0,
            "leftRotation": 0,
            "rightRotation": 0,
            "faceScale": 0.74,
            "faceY": 0,
            "rotationX": 0,
            "rotationY": 0,
            "rotationZ": 0,
            "squash": 1,
            "tongue": false,
            "teeth": false,
            "drool": false,
            "cheeks": false,
            "tears": false,
            "mouthStroke": 1.6
          }
        }
      ]
    }
  ],
  "animations": [
    {
      "id": "idle",
      "name": "Idle",
      "loop": true,
      "steps": [
        {
          "id": "idle-step-1",
          "expressionId": "idle",
          "duration": 5
        }
      ]
    },
    {
      "id": "listening",
      "name": "Listening",
      "loop": true,
      "steps": [
        {
          "id": "listening-step-1",
          "expressionId": "listening",
          "duration": 3.8
        },
        {
          "id": "listening-step-2",
          "expressionId": "idle",
          "duration": 1.6
        }
      ]
    },
    {
      "id": "thinking",
      "name": "Thinking",
      "loop": true,
      "steps": [
        {
          "id": "thinking-step-1",
          "expressionId": "thinking",
          "duration": 4.3
        },
        {
          "id": "thinking-step-2",
          "expressionId": "working",
          "duration": 1.8
        }
      ]
    },
    {
      "id": "working",
      "name": "Working",
      "loop": true,
      "steps": [
        {
          "id": "working-step-1",
          "expressionId": "working",
          "duration": 6.8
        },
        {
          "id": "working-step-2",
          "expressionId": "thinking",
          "duration": 2.2
        }
      ]
    },
    {
      "id": "happy",
      "name": "Success",
      "loop": true,
      "steps": [
        {
          "id": "happy-step-1",
          "expressionId": "happy",
          "duration": 3.7
        },
        {
          "id": "happy-step-2",
          "expressionId": "playful",
          "duration": 2.4
        },
        {
          "id": "happy-step-3",
          "expressionId": "idle",
          "duration": 1.8
        }
      ]
    },
    {
      "id": "confused",
      "name": "Confused",
      "loop": true,
      "steps": [
        {
          "id": "confused-step-1",
          "expressionId": "confused",
          "duration": 3.9
        },
        {
          "id": "confused-step-2",
          "expressionId": "thinking",
          "duration": 2.1
        }
      ]
    },
    {
      "id": "sleepy",
      "name": "Sleepy",
      "loop": true,
      "steps": [
        {
          "id": "sleepy-step-1",
          "expressionId": "sleepy",
          "duration": 6
        }
      ]
    },
    {
      "id": "playful",
      "name": "Playful",
      "loop": true,
      "steps": [
        {
          "id": "playful-step-1",
          "expressionId": "playful",
          "duration": 3.6
        },
        {
          "id": "playful-step-2",
          "expressionId": "happy",
          "duration": 2.2
        }
      ]
    },
    {
      "id": "animation-078668cd",
      "name": "New animation",
      "loop": true,
      "steps": [
        {
          "id": "step-fde801f7",
          "expressionId": "working",
          "duration": 3.4
        }
      ]
    },
    {
      "id": "loading",
      "name": "Loading",
      "loop": true,
      "steps": [
        {
          "id": "step-5fd1d737",
          "expressionId": "loading",
          "duration": 2.5
        }
      ]
    },
    {
      "id": "animation-0dd1e312",
      "name": "Listening 2",
      "loop": true,
      "steps": [
        {
          "id": "step-31c18790",
          "expressionId": "idle",
          "duration": 5
        },
        {
          "id": "step-48e70fa6",
          "expressionId": "listening",
          "duration": 3.8000000000000003
        }
      ]
    },
    {
      "id": "animation-c1df7072",
      "name": "idle side to side 01",
      "loop": true,
      "steps": [
        {
          "id": "step-dd427653",
          "expressionId": "expression-7287c053",
          "duration": 6
        }
      ]
    },
    {
      "id": "animation-0efb6f80",
      "name": "idle side to side 02",
      "loop": true,
      "steps": [
        {
          "id": "step-a000b372",
          "expressionId": "expression-f9a89083",
          "duration": 6
        }
      ]
    },
    {
      "id": "animation-9386f24d",
      "name": "idle side to side 03",
      "loop": true,
      "steps": [
        {
          "id": "step-04145e45",
          "expressionId": "expression-b20a0ef7",
          "duration": 6
        }
      ]
    },
    {
      "id": "animation-2f02a915",
      "name": "sleepy to wake",
      "loop": false,
      "steps": [
        {
          "id": "step-7fa9addf",
          "expressionId": "expression-229a39b6",
          "duration": 5.2
        }
      ]
    }
  ]
} as unknown as Definition;
