// Generated by scripts/generate-acpx-sidecar-contract.mjs. Do not edit.

pub const GENERATED_ACPX_SIDECAR_PROTOCOL_VERSION: u64 = 2;

pub const GENERATED_ACPX_TOOL_OPERATION_PRECEDENCE: &[(&str, &[&str])] = &[
    ("edit", &["edit", "write", "patch"]),
    ("read", &["read"]),
    ("search", &["search", "grep", "find"]),
    ("list", &["list", "glob"]),
];

pub fn classify_generated_acpx_tool_operation(kind: &str, title: &str) -> &'static str {
    let kind = kind.to_ascii_lowercase();
    let title = title.to_ascii_lowercase();
    let candidate = if kind.is_empty() { &title } else { &kind };
    for (operation, tokens) in GENERATED_ACPX_TOOL_OPERATION_PRECEDENCE {
        if tokens.iter().any(|token| candidate.contains(token)) {
            return operation;
        }
    }
    if candidate.is_empty() {
        "unknown"
    } else {
        "execute"
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GeneratedAcpxSidecarCommand {
    Initialize,
    SessionOpen,
    RunAttach,
    TurnStart,
    TurnCancel,
    PermissionResolve,
    InputResolve,
    ToolResolve,
    SessionRead,
    SessionSnapshot,
    SessionGoalGet,
    SessionGoalSet,
    SessionGoalClear,
    SessionSuspend,
    SessionClose,
}

impl GeneratedAcpxSidecarCommand {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Initialize => "initialize",
            Self::SessionOpen => "session.open",
            Self::RunAttach => "run.attach",
            Self::TurnStart => "turn.start",
            Self::TurnCancel => "turn.cancel",
            Self::PermissionResolve => "permission.resolve",
            Self::InputResolve => "input.resolve",
            Self::ToolResolve => "tool.resolve",
            Self::SessionRead => "session.read",
            Self::SessionSnapshot => "session.snapshot",
            Self::SessionGoalGet => "session.goal.get",
            Self::SessionGoalSet => "session.goal.set",
            Self::SessionGoalClear => "session.goal.clear",
            Self::SessionSuspend => "session.suspend",
            Self::SessionClose => "session.close",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Deserialize)]
pub enum GeneratedAcpxSidecarEventType {
    #[serde(rename = "runtime.event")]
    RuntimeEvent,
    #[serde(rename = "runtime.permission_requested")]
    RuntimePermissionRequested,
    #[serde(rename = "runtime.input_requested")]
    RuntimeInputRequested,
    #[serde(rename = "runtime.tool_called")]
    RuntimeToolCalled,
    #[serde(rename = "runtime.turn_terminal")]
    RuntimeTurnTerminal,
    #[serde(rename = "runtime.process")]
    RuntimeProcess,
    #[serde(rename = "runtime.diagnostic")]
    RuntimeDiagnostic,
    #[serde(rename = "runtime.goal")]
    RuntimeGoal,
}
