// Generated by scripts/generate-acpx-sidecar-contract.mjs. Do not edit.

export const GENERATED_ACPX_SIDECAR_PROTOCOL_VERSION = 2 as const;
export const GENERATED_ACPX_SIDECAR_COMMANDS = [
  "initialize",
  "session.open",
  "run.attach",
  "turn.start",
  "turn.cancel",
  "permission.resolve",
  "input.resolve",
  "tool.resolve",
  "session.read",
  "session.snapshot",
  "session.goal.get",
  "session.goal.set",
  "session.goal.clear",
  "session.suspend",
  "session.close",
] as const;
export type GeneratedAcpxSidecarCommand =
  (typeof GENERATED_ACPX_SIDECAR_COMMANDS)[number];

export const GENERATED_ACPX_SIDECAR_EVENT_TYPES = [
  "runtime.event",
  "runtime.permission_requested",
  "runtime.input_requested",
  "runtime.tool_called",
  "runtime.turn_terminal",
  "runtime.process",
  "runtime.diagnostic",
  "runtime.goal",
] as const;
export type GeneratedAcpxSidecarEventType =
  (typeof GENERATED_ACPX_SIDECAR_EVENT_TYPES)[number];

export type GeneratedAcpxToolOperation =
  | "read"
  | "search"
  | "list"
  | "edit"
  | "execute"
  | "unknown";

export const GENERATED_ACPX_TOOL_OPERATION_PRECEDENCE = [
  { operation: "edit", tokens: ["edit", "write", "patch"] },
  { operation: "read", tokens: ["read"] },
  { operation: "search", tokens: ["search", "grep", "find"] },
  { operation: "list", tokens: ["list", "glob"] },
] as const;

function lowercaseGeneratedAcpxAscii(value: string): string {
  return value.replace(/[A-Z]/g, (character) =>
    String.fromCharCode(character.charCodeAt(0) + 32),
  );
}

export function classifyGeneratedAcpxToolOperation(
  toolKind: unknown,
  toolTitle: unknown,
): GeneratedAcpxToolOperation {
  const candidate =
    typeof toolKind === "string" && toolKind
      ? toolKind
      : typeof toolTitle === "string"
        ? toolTitle
        : "";
  const normalized = lowercaseGeneratedAcpxAscii(candidate);
  for (const { operation, tokens } of GENERATED_ACPX_TOOL_OPERATION_PRECEDENCE) {
    if (tokens.some((token) => normalized.includes(token))) return operation;
  }
  return normalized ? "execute" : "unknown";
}
